// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnPvzPzxIjezjUx_X1JUoQTGSglAfIt-c',
    appId: '1:1054140795203:android:f21d6ed1be203027d307f6',
    messagingSenderId: '1054140795203',
    projectId: 'edmyn-dev',
    storageBucket: 'edmyn-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfau_EKjQ4FgBrgt3NtgwnigAW-phaNGU',
    appId: '1:1054140795203:ios:fbea58c72e6dd652d307f6',
    messagingSenderId: '1054140795203',
    projectId: 'edmyn-dev',
    storageBucket: 'edmyn-dev.appspot.com',
    androidClientId: '1054140795203-ts494j6kqp2lf9umrlm17c2512kujl64.apps.googleusercontent.com',
    iosClientId: '1054140795203-4cgci5t8dkhkcltibbfeqq9e8lkcg9gs.apps.googleusercontent.com',
    iosBundleId: 'com.edmyn.edmyn',
  );
}
